module.exports.names = [
    'Touka Kirishima',
    'Shion',
    'Faye Valentine',
    'Shura Kirigakure',
    'Android 18',
    'Shoko Nishimiya',
    'Misato Katsuragi',
    'Tsunade Senju',
    'Azusa Hamaoka',
    'Utahime Iori',
    'Raphtalia',
    'Fubuki',
    'Ayame Himuro',
    'Revy',
    'Darkness',
    'Miruko',
    'Casca',
    'Nami',
    'Fern',
    'Makima',
    'Mitsuri Kanroji',
    'Maki Oze',
    'Mirajane',
    'Saber',
    'Kurisu Makise',
    'Esdeath',
    'Kaguya Otsutsuki',
    'Kanzaki Kaori',
    'Yoruichi Shihoin',
    'Kagome Higurashi',
    'Mikasa Ackerman',
    'Power',
    'Zero Two',
    'Erza Scarlet',
    'Hinata Hyuga',
    'Rem',
    'Orihime Inoue',
    'Asuna Yuuki',
    'Casca',
    'Satsuki Kiryuuin',
    'Lucoa',
    'Yoko Litter',
    'Rias Gremory',
    'Akeno Himejima',
    'Rangiku Matsumoto',
    'Lucy Heartfilia',
    'Albedo',
    'Hotaru Shidare',
    'Meiko Shiraki',
    'Anna Nishikinomiya'
]
